# week08/k8s/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: ecomm-secrets-w08e1
type: Opaque # Indicates arbitrary user-defined data
data:
  # PostgreSQL Credentials (for both Product DB and Order DB)
  POSTGRES_USER: "cG9zdGdyZXM=" # Base64 for 'postgres'
  POSTGRES_PASSWORD: "cG9zdGdyZXM=" # Base64 for 'postgres'

  # Azure Storage Account Credentials for Product Service image uploads
  # REPLACE WITH YOUR ACTUAL BASE64 ENCODED VALUES from your Azure Storage Account
  # Example: echo -n 'eIc4A75cornqEV+ZvQ1Su9sRLdLmRvBBrJP98GwdMCqbjRSenS3bT2cJWZndxJzwbdKQyrswzozd+AStVVVFiQ==' | base64
  AZURE_STORAGE_ACCOUNT_NAME: "YXN0cm9zdG9yYWdld2Vlaw==" 
  AZURE_STORAGE_ACCOUNT_KEY: "ZUljNEE3NWNvcm5xRVYrWnZRMVN1OXNSTGRMbVJ2QkJySlA5OEd3ZE1DcWJqUlNlblMzYlQyY0pXWm5keEp6d2JkS1F5cnN3em96ZCtBU3RWVlZGaVE9PQ=="
